language: php
php:
  - 7.1
  - 7.2
  - 7.3

branches:
  only:
    - master

install:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - cd tests
  - ../vendor/bin/phpunit --coverage-clover ../build/logs/clover.xml --configuration phpunit.xml

after_script:
  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)
